import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import type { AppConfig } from "../config.js";
import { codexRolloutAdapter } from "../middlewares/trace/codex-rollout.js";
import type { RunnerRequest } from "../types.js";
import type { ParsedEvents, RuntimeDefinition } from "./types.js";

export function buildCodexArgs(
  request: RunnerRequest,
  sandboxMode: AppConfig["codexSandboxMode"],
  workspacePath = request.workspacePath,
): string[] {
  const args = [
    "exec",
    "--json",
    "--sandbox",
    sandboxMode,
    "--skip-git-repo-check",
    "-C",
    workspacePath,
  ];
  if (request.threadId) {
    args.push("resume", request.threadId, request.prompt);
  } else {
    args.push(request.prompt);
  }
  return args;
}

export function parseCodexEventLine(
  line: string,
  parsed: ParsedEvents,
  onEvent?: (event: Record<string, unknown>) => void,
): void {
  let event: Record<string, unknown>;
  try {
    event = JSON.parse(line) as Record<string, unknown>;
  } catch {
    return;
  }

  onEvent?.(event);

  if (event.type === "thread.started" && typeof event.thread_id === "string") {
    parsed.threadId = event.thread_id;
  }

  if (event.type === "item.completed" && event.item && typeof event.item === "object") {
    const item = event.item as Record<string, unknown>;
    if (item.type === "agent_message" && typeof item.text === "string") {
      parsed.messages.push(item.text);
    }
  }

  if (event.type === "turn.completed" && event.usage && typeof event.usage === "object") {
    const usage = event.usage as Record<string, unknown>;
    parsed.usage = {
      ...(typeof usage.input_tokens === "number"
        ? { inputTokens: usage.input_tokens }
        : {}),
      ...(typeof usage.cached_input_tokens === "number"
        ? { cachedInputTokens: usage.cached_input_tokens }
        : {}),
      ...(typeof usage.output_tokens === "number"
        ? { outputTokens: usage.output_tokens }
        : {}),
    };
  }

  const streamError = readStreamError(event);
  if (streamError !== null) {
    parsed.errors.push(streamError);
  }
}

// One definition of "this event reports a failure", shared by the runner and
// the trace service. They used to disagree — only the trace side counted
// `turn.failed` — so the same run could report two different error counts and
// the evidence could miss the event that said what actually went wrong.
export function readStreamError(
  event: Record<string, unknown>,
): string | null {
  if (event.type === "error") {
    if (typeof event.message === "string" && event.message.length > 0) {
      return event.message;
    }
    if (typeof event.error === "string" && event.error.length > 0) {
      return event.error;
    }
    return "Codex reported an unknown error";
  }
  if (event.type === "turn.failed") {
    const detail = event.error;
    if (typeof detail === "string" && detail.length > 0) return detail;
    if (detail !== null && typeof detail === "object" && "message" in detail) {
      const message = (detail as { message?: unknown }).message;
      if (typeof message === "string" && message.length > 0) return message;
    }
    return "The Codex turn failed";
  }
  return null;
}

export const codexRuntime: RuntimeDefinition = {
  id: "codex",
  bin: (config) => config.codexBin,
  homeDir: (config) => config.codexHome,
  homeEnvVar: "CODEX_HOME",

  buildArgs: (request, workspacePath, config) =>
    buildCodexArgs(request, config.codexSandboxMode, workspacePath),

  parseEventLine: parseCodexEventLine,

  async bootstrap(config) {
    await mkdir(config.codexHome, { recursive: true });
    const toml = [
      "# Generated by Volc Agent Launchpad. Edit environment variables, not this file.",
      "model = " + JSON.stringify(config.arkModel || "ep-not-configured"),
      'model_provider = "volcengine_ark"',
      "",
      "[model_providers.volcengine_ark]",
      'name = "Volcengine Ark"',
      "base_url = " + JSON.stringify(config.arkBaseUrl),
      'env_key = "ARK_API_KEY"',
      'wire_api = "responses"',
      "requires_openai_auth = false",
      "",
    ].join("\n");
    await writeFile(path.join(config.codexHome, "config.toml"), toml, {
      encoding: "utf8",
      mode: 0o600,
    });
  },

  processEnv: (config) => ({
    CODEX_HOME: config.codexHome,
    ARK_API_KEY: config.arkApiKey,
  }),

  trace: {
    runtimeId: "codex",
    displayName: "Codex",
    ...codexRolloutAdapter,
  },
};
